fos_ck_editor:
    default_config: my_config
    configs:
        my_config:
            uiColor:                "#ffffff"

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
