hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        azure:
            type:          azure
            client_id:     '%env(AZURE_CLIENT_ID)%'
            client_secret: '%env(AZURE_SECRET)%'

            scope: 'openid profile email offline_access User.Read'
            options:
                application: '%env(AZURE_TENANT_ID)%'
