knp_menu:
  twig:
    template: '_partials/menu.html.twig'
  #  if true, enables the helper for PHP templates
  templating: false
  # the renderer to use, list is also available by default
  default_renderer: twig

services:
  _defaults:
    autowire: true
    autoconfigure: true
