framework:
    cache:
        pools:
            liip_cache:
                adapter: cache.adapter.redis

services:
    liip_imagine.cache.resolver.psr:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\PsrCacheResolver
        arguments:
            - "@liip_cache"
            - "@liip_imagine.cache.resolver.generic"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "psr_cache" }

# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    webp:
        generate: true

    resolvers:
        generic:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'
        flysystem:
            flysystem:
                filesystem_service: oneup_flysystem.default_filesystem_filesystem
        chain:
            chain:
                # use the "foo", "bar", and "baz" loaders
                loaders:
                    - default
                    - flysystem

    data_loader: chain

    cache: psr_cache

    filter_sets :
        optimized :
            quality : 99

        # the name of the "filter set"
        sponsor_index:
            quality: 90
            filters:
                thumbnail:
                    size: [ 118, 58 ]
                    mode: inset
                background:
                    size: [ 120, 60 ]
                    position: center
                    transparency: 100

        sponsor_index_main:
            quality: 90
            filters:
                thumbnail:
                    size: [ 256, 127 ]
                    mode: inset
                background:
                    size: [ 258, 129 ]
                    position: center
                    transparency: 100

        # the name of the "filter set"
        sponsor_main:
            quality: 90
            filters:
                thumbnail:
                    size: [ 380, 190 ]
                    mode: inset
                background:
                    size: [ 420, 220 ]
                    position: center

        sponsor_page:
            quality: 90
            filters:
                thumbnail:
                    size: [ 245, 122 ]
                    mode: inset
                background:
                    size: [ 257, 124 ]
                    position: center

    twig:
        mode: lazy
