security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # the name of your user provider can be anything
        your_custom_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|media)/
            security: false

        main:
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                enable_csrf: true
                default_target_path: app_admin_index

            oauth:
                resource_owners:
                    azure: azure_login
                login_path:   app_admin_login
                use_forward:  false
                failure_path: app_admin_login
                default_target_path: app_admin_index

                oauth_user_provider:
                    service: App\Security\UserProvider

            entry_point: form_login

            logout:
                path: app_admin_logout
                target: app_admin_login

    access_control:
         - { path: ^/admin/login, roles: PUBLIC_ACCESS }
         - { path: ^/admin, roles: ROLE_USER }
         - { path: ^/connect, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
