security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users:
            entity:
                class: App\Storage\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|media)/
            security: false

        main:
            # ...
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                enable_csrf: true
                default_target_path: app_admin_index

            logout:
                path: app_admin_logout
                target: app_index

    access_control:
         - { path: ^/admin/login, roles: PUBLIC_ACCESS }
         - { path: ^/admin, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
