twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Module/Admin/Templates': 'admin'
        '%kernel.project_dir%/src/Module/Page/Templates': 'page'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@TbbcMoney/Form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
