services:
  app:
    image: thecodingmachine/php:8.3-v4-apache-node20
    volumes:
      - .:/var/www/html
      - ./var/.bash_history:/home/docker/.bash_history
      - ${HOME}/.composer/:/home/docker/.composer/
    environment:
      - TZ=Europe/Berlin
      - APP_ENV=dev
      - APP_DEBUG=true
      - APACHE_DOCUMENT_ROOT=public
      - PHP_EXTENSION_BCMATH=1
      - PHP_EXTENSION_IMAGICK=1
      - PHP_EXTENSION_INTL=1
      - PHP_EXTENSION_GD=1
      - PHP_INI_MEMORY_LIMIT=2048m
      - PHP_INI_UPLOAD_MAX_FILESIZE=50m
      - PHP_INI_POST_MAX_SIZE=50m
    depends_on:
      - database
    networks:
      internal:
        ipv4_address: 192.168.19.10

  database:
    image: mariadb:lts
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      internal:
        ipv4_address: 192.168.19.11

  mailpit:
    image: axllent/mailpit
    networks:
      internal:
        ipv4_address: 192.168.19.12

  redis:
    image: redis
    networks:
      internal:
        ipv4_address: 192.168.19.13

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    networks:
      internal:
        ipv4_address: 192.168.19.14

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.19.0/24
