version: '3.6'

services:
  app:
    image: thecodingmachine/php:8.1-v4-apache-node16
    volumes:
      - .:/var/www/html
      - ./var/.bash_history:/home/docker/.bash_history
      - ${HOME}/.composer/:/home/docker/.composer/
    environment:
      - TZ=Europe/Berlin
      - APP_ENV=dev
      - APP_DEBUG=true
      - APACHE_DOCUMENT_ROOT=public
      - PHP_EXTENSION_BCMATH=1
      - PHP_EXTENSION_IMAGICK=1
      - PHP_EXTENSION_INTL=1
      - PHP_EXTENSION_GD=1
    depends_on:
      - database
    networks:
      internal:
        ipv4_address: 192.168.19.10

  database:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      internal:
        ipv4_address: 192.168.19.11

  mailhog:
    image: mailhog/mailhog
    networks:
      internal:
        ipv4_address: 192.168.19.12

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.19.0/24
