services:
  app:
    image: thecodingmachine/php:8.4-v4-apache
    volumes:
      - .:/var/www/html
      - ./var/.bash_history:/home/docker/.bash_history
      - ${HOME}/.composer/:/home/docker/.composer/
    environment:
      - TZ=Europe/Berlin
      - APP_ENV=dev
      - APP_DEBUG=true
      - APACHE_DOCUMENT_ROOT=public
      - PHP_EXTENSION_BCMATH=1
      - PHP_EXTENSION_IMAGICK=1
      - PHP_EXTENSION_INTL=1
      - PHP_EXTENSION_GD=1
      - PHP_INI_MEMORY_LIMIT=2048m
      - PHP_INI_UPLOAD_MAX_FILESIZE=50m
      - PHP_INI_POST_MAX_SIZE=50m
    depends_on:
      - database
    networks:
      internal:
        ipv4_address: 192.168.19.10

  node:
    image: guergeiro/pnpm:lts-latest-alpine
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy
    container_name: imgproxy
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      IMGPROXY_KEY: 2d5e052902893310f94a568c604a2de540a3966b92da89eed8d153f6ed3b2775787e2e057093ccf1dbb5449bfff14d0b4f74195bfbd22e844e87892f2b032513
      IMGPROXY_SALT: 01ccf236bc7771b3f4b66a0d6b5d623801fa96b1404b2c7ca91c816f6f20a22644c7dbb926fa4c288f3c458d7425f29fb33763ce8f7a821cde68ec2d22ba9b60
      IMGPROXY_AUTO_WEBP: true
      IMGPROXY_AUTO_AVIF: true
      IMGPROXY_AUTO_JXL: true
      IMGPROXY_LOG_LEVEL: info
    networks:
      - internal

  database:
    image: mariadb:lts
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - internal

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      internal:
        ipv4_address: 192.168.19.12

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.19.0/24
