page:
    resource: ../src/Module/Page/Controller/
    type: attribute

admin:
    resource: ../src/Module/Admin/Controller/
    type: attribute
    prefix: admin

app_admin_logout:
    path: /admin/logout
    methods: GET
