services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Storage/Entity/'
            - '../src/Kernel.php'

    StellaMaris\Clock\ClockInterface:
        factory: '@App\Infrastructure\Clock\ClockFactory'
